# Generated by Django 4.2.4 on 2023-08-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TasksApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="sub_tasks",
            field=models.ManyToManyField(blank=True, to="TasksApp.task"),
        ),
    ]
