# Generated by Django 4.2.4 on 2023-08-30 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('TasksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(related_name='executors', to='Users.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tasks', to='TasksApp.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_tasks',
            field=models.ManyToManyField(blank=True, related_name='super_task', to='TasksApp.task'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='check_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TasksApp.checklist'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TasksApp.task'),
        ),
    ]
