# Generated by Django 4.2.4 on 2023-08-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TasksApp", "0002_task_sub_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="check_list",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="TasksApp.checklist",
            ),
            preserve_default=False,
        ),
    ]
