# Generated by Django 4.2.4 on 2023-08-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_tasks',
        ),
    ]
