# Generated by Django 4.2.4 on 2023-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TasksApp", "0003_checklistitem_check_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="done_dt",
            field=models.DateTimeField(null=True),
        ),
    ]
