# Generated by Django 4.2.4 on 2023-08-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('TasksApp', '0003_remove_task_sub_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created', 'updated', 'deadline']},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_lists', to='TasksApp.task'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='check_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='TasksApp.checklist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(related_name='related_tasks', to='Users.profile'),
        ),
    ]
