# Generated by Django 4.2.4 on 2023-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TasksApp", "0004_task_done_task_done_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="name",
            field=models.CharField(default="Null", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="done_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
