# Generated by Django 4.2.4 on 2023-08-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0005_checklist_name_alter_task_done_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
