# Generated by Django 4.2.4 on 2023-08-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('TasksApp', '0006_remove_profile_group_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(related_name='executors', to='Users.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
