# Generated by Django 4.2.4 on 2023-08-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0007_alter_task_author_alter_task_executors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task_fk', to='TasksApp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sub_tasks',
            field=models.ManyToManyField(blank=True, related_name='sub_tasks_fk', to='TasksApp.task'),
        ),
    ]
