services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # cache:
  #   image: redis
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server
  #   volumes:
  #     - cache:/data

volumes:
  postgres_volume:
  # cache:
  #   driver: local