services:


  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint:
      - /backend/entrypoint-web.sh
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis


  db:
    ports:
      - 5432:5432
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


  celery_worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint:
      - /backend/entrypoint-worker.sh
    depends_on:
      - redis
      - web

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis:/data

volumes:
  postgres_volume:
  redis:
    driver: local